### PR TITLE
Create give_a_talk.yml

### PR DESCRIPTION
**Pull request by Arielle-Bennett**
Adding the give a talk issue template from the main repo to the conferences repo.

Hopefully this looks okay and runs correctly :D

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
Let's go ahead and merge this, there is really no other way to test it.

**Comment by da5nsy** [comment]
Looks like this works fine. However, this repo doesn't have [`.github/workflows/close-talk-issues.yml`](https://github.com/the-turing-way/the-turing-way/blob/main/.github/workflows/close-talk-issues.yml) and so as things stand the final bit about automated closing is not correct. We could either add that workflow to this repo, or remove that section of the text.

**Comment by da5nsy** [comment]
Do we want to have this template on both repos? My guess would be no, and that it would be better to direct people to use one or the other. We could replace the template in the main repo with a link to create an issue on this repo perhaps?

**Comment by da5nsy** [comment]
Also flagging an open PR which suggests changes to this file: https://github.com/the-turing-way/the-turing-way/pull/2106

**Comment by KirstieJane** [comment]
> Do we want to have this template on both repos? My guess would be no, and that it would be better to direct people to use one or the other. We could replace the template in the main repo with a link to create an issue on this repo perhaps?

I think sending folks to this repo sounds really sensible! I'd be open to others saying that it makes the flow more confusing? But I think a 2025 goal is to not have an overwhelming number of issues all in one repo, right? So a nudge to this one seems the best way forwards 😄

**Comment by bsipocz** [comment]
> Do we want to have this template on both repos?

Nope, there should be only in the one where the talk would eventually live. Or maybe just have a  "Note" template? E.g. they can choose the talk as an option in the main repo, but then the template is a link to this repo instead? (But I don't think it's a good option, only a handful of people will/should open these PRs and they will all use to the fact that we stepped away from having a monorepo really fast)

**Pull request merged**
